# Generated by Django 6.0.3 on 2026-03-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.AlterField(
            model_name='project',
            name='tecnologia',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
